/*
 * Copyright 2019 NXP.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: LPC55S69
mcu_data: ksdk2_0
processor_version: 0.1.11
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "pin_mux.h"
#include "fsl_iocon.h"
#include "fsl_gpio.h"



/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    GPIO_PortInit(GPIO, 0U);
    GPIO_PortInit(GPIO, 1U);


    const uint32_t uart6_pin_config = (
									IOCON_PIO_FUNC(2) |
									/* No addition pin function */
									IOCON_PIO_MODE(0) |
									/* Standard mode, output slew rate control is enabled */
									IOCON_PIO_SLEW(0) |
									/* Input function is not inverted */
									IOCON_PIO_INVERT(0) |
									/* Enables digital function */
									IOCON_PIO_DIGIMODE(1) |
									/* Open drain is disabled */
									IOCON_PIO_OD(0));

    IOCON_PinMuxSet(IOCON, 1U, 13U, uart6_pin_config);
    IOCON_PinMuxSet(IOCON, 1U, 16U, uart6_pin_config);

    const uint32_t gpio_pin_config = (
									IOCON_PIO_FUNC(0) |
									/* No addition pin function */
									IOCON_PIO_MODE(0) |
									/* Standard mode, output slew rate control is enabled */
									IOCON_PIO_SLEW(0) |
									/* Input function is not inverted */
									IOCON_PIO_INVERT(0) |
									/* Enables digital function */
									IOCON_PIO_DIGIMODE(1) |
									/* Open drain is disabled */
									IOCON_PIO_OD(0));
    IOCON_PinMuxSet(IOCON, 0U, 18U, gpio_pin_config);
    IOCON_PinMuxSet(IOCON, 1U, 23U, gpio_pin_config); // Enable ESP32

    gpio_pin_config_t xgpioConfig = {.pinDirection = kGPIO_DigitalOutput, .outputLogic = 1};
    GPIO_PinInit(GPIO, 0U, 18U, &(xgpioConfig));
    GPIO_PinInit(GPIO, 1U, 23U, &(xgpioConfig));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
